import { Application } from "../declarations";
import users from "./users/users.service";
import forgetPassword from "./forget-password/forget-password.service";
import lock from "./lock/lock.service";
import courses from "./courses/courses.service";
import arrayState from "./array-state/array-state.service";
import upload from "./upload/upload.service";
import enrolCourse from "./enrol-course/enrol-course.service";
import coursePreview from "./course-preview/course-preview.service";
import countries from "./countries/countries.service";
import publishedCourses from "./published-courses/published-courses.service";
import notifications from "./notifications/notifications.service";
import categories from "./categories/categories.service";
import userExport from "./user-export/user-export.service";
import coursesReportService from "./courses-report/courses-report.service";
import emailFinderService from "./email-finder/email-finder.service";
import notificationScheduler from "./notification-scheduler/notification-scheduler.service";
import locations from "./locations/locations.service";
import authorCourses from "./authors/courses";
import adminClasses from "./admin-classes/admin-classes.service";
import teacherClasses from "./teacher-classes/teacher-classes.service";
import schools from "./schools/schools.service";
import signup from "./signup/signup.service";
import classes from "./classes/classes.service";
import classEnrollments from "./class-enrollments/class-enrollments.service";
import classTeachers from "./class-teachers/class-teachers.service";
import courseSections from "./course-sections/course-sections.service";
import lessons from "./lessons/lessons.service";
// Don't remove this comment. It's needed to format import lines nicely.

export default function (app: Application): void {
  app.configure(users);
  app.configure(forgetPassword);
  app.configure(lock);
  app.configure(courses);
  app.configure(upload);
  app.configure(arrayState);
  app.configure(upload);
  app.configure(enrolCourse);
  app.configure(coursePreview);
  app.configure(countries);
  app.configure(publishedCourses);
  app.configure(notifications);
  app.configure(categories);
  app.configure(userExport);
  app.configure(coursesReportService);
  app.configure(emailFinderService);
  app.configure(notificationScheduler);
  app.configure(locations);
  app.configure(authorCourses);
  app.configure(adminClasses);
  app.configure(teacherClasses);
  app.configure(schools);
  app.configure(signup);
  app.configure(classes);
  app.configure(classEnrollments);
  app.configure(classTeachers);
  app.configure(courseSections);
  app.configure(lessons);
}
